CONTAINER Daylight
{
    NAME Daylight;
    INCLUDE Obase;


    GROUP ID_OBJECTPROPERTIES_DL
    {

        DEFAULT 1;

        STRING DL_RENDERER { ANIM OFF; CUSTOMGUI STATICTEXT; WORDWRAP;}

        GROUP{COLUMNS 2; SCALE_H;

            STATICTEXT DL_PE {SCALE_H;}
            BUTTON DL_HELP { SCALE_H;}

        }

        SEPARATOR DL_POSITION_SUN { SCALE_H; }
        SEPARATOR { SCALE_H; }

        GROUP{

            SEPARATOR { SCALE_H;}
            REAL DL_ROT_X {SCALE_H; ANIM OFF; MIN -360.0; MINEX; MAX 360.0; MAXEX; MINSLIDER -360.0; MAXSLIDER 360.0; STEP 1.0; UNIT DEGREE; CUSTOMGUI REALSLIDER;}
            REAL DL_ROT_Y {SCALE_H; ANIM OFF; MIN 0.0; MINEX; MAX 90.0; MAXEX; MINSLIDER 0.0; MAXSLIDER 90.0; STEP 1.0; UNIT DEGREE; CUSTOMGUI REALSLIDER;}

        }

        SEPARATOR DL_SUN_SETTINGS { SCALE_H; }
        SEPARATOR { SCALE_H;}

        GROUP{

            SEPARATOR { SCALE_H;}

            COLOR DL_LIGHT_COLOR { OPEN; PARENTCOLLAPSE; }

            SEPARATOR { SCALE_H;}

            REAL DL_BRIGHTNESS {SCALE_H; MIN 0.0; MINEX; MAX 10000.0; MAXEX; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 1.0; UNIT PERCENT; CUSTOMGUI REALSLIDER;}

        }

        SEPARATOR DL_SHADOW_SET{ SCALE_H; }
        SEPARATOR { SCALE_H; }

        GROUP{

            SEPARATOR { SCALE_H; }

            LONG DL_LIGHT_SHADOWTYPE { CYCLE { DL_TRACE; DL_AREA;}; ANIM OFF;}
            REAL DL_SHADOW_DENSITY {SCALE_H; MIN 0.0; MINEX; MAX 300.0; MAXEX; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 1.0; UNIT PERCENT; CUSTOMGUI REALSLIDER;}

            SEPARATOR { SCALE_H; }

            GROUP {COLUMNS 2; SCALE_H;

                BOOL DL_LOCK {SCALE_H; ANIM OFF;}
                COLOR DL_SHADOW_COLOR { PARENTCOLLAPSE; ANIM OFF;}
            }

            SEPARATOR { SCALE_H; }

            REAL DL_SHADOW_HUE {SCALE_H; MIN 0.0; MINEX; MAX 100.0; MAXEX; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 1.0; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
            REAL DL_SHADOW_BRIGHTNESS {SCALE_H; MIN 0.0; MINEX; MAX 100.0; MAXEX; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 1.0; UNIT PERCENT; CUSTOMGUI REALSLIDER;}

        }

        SEPARATOR DL_FOG_SET{ SCALE_H; }
        SEPARATOR { SCALE_H; }

        GROUP{

            SEPARATOR { SCALE_H; }

            BOOL DL_USED_FOG {SCALE_H; ANIM OFF;}

            REAL DL_FOG_STR {SCALE_H; MIN 0.0; MINEX; MAX 100.0; MAXEX; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 1.0; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
            REAL DL_FOG_DISTANCE {SCALE_H; MIN 0.0; MINEX; MAX 100000000.0; MAXEX; MINSLIDER 0.0; MAXSLIDER 1000000.0; STEP 1000.0; UNIT METER; CUSTOMGUI REALSLIDER;}

            SEPARATOR { SCALE_H; }

            GROUP {COLUMNS 2; SCALE_H;

                BOOL DL_LOCK_FOG {SCALE_H; ANIM OFF;}
                COLOR DL_FOG_COLOR { PARENTCOLLAPSE; ANIM OFF;}

            }

            REAL DL_FOG_HUE {SCALE_H; MIN 0.0; MINEX; MAX 100.0; MAXEX; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 1.0; UNIT PERCENT; CUSTOMGUI REALSLIDER;}

        }


        SEPARATOR DL_VIEWPORT{ SCALE_H; }
        SEPARATOR { SCALE_H; }

        GROUP{

            SEPARATOR { SCALE_H; }

            GROUP {COLUMNS 2; SCALE_H;

                BOOL DL_SHOW_IN_VIEWPORT {SCALE_H; ANIM OFF;}
                BOOL DL_SHOW_FOG {SCALE_H; ANIM OFF;}

            }

        }


    }


}