CONTAINER Floor
{
    NAME Floor;
    INCLUDE Obase;


    GROUP ID_OBJECTPROPERTIES_IF
    {

        DEFAULT 1;

        STRING IF_RENDERER { ANIM OFF; CUSTOMGUI STATICTEXT; WORDWRAP;}

        GROUP{COLUMNS 2; SCALE_H;

            STATICTEXT IF_PE {SCALE_H;}
            BUTTON IF_HELP { SCALE_H;}

        }

        SEPARATOR IF_MODE_SET { SCALE_H; }
        SEPARATOR { SCALE_H; }

        GROUP{

            SEPARATOR { SCALE_H; }

            LONG IF_FLOOR_MODE { CYCLE { IF_F_INFINITE; IF_F_STUDIO;}; SCALE_H; ANIM OFF;}
            REAL IF_SIZE_F_STUDIO {SCALE_H; ANIM OFF; MIN 0.0; MINEX; MAX 100000.0; MAXEX; MINSLIDER 0.0; MAXSLIDER 10000.0; STEP 0.01; UNIT METER; CUSTOMGUI REALSLIDER;}

        }

        SEPARATOR IF_GRADIENT_SET { SCALE_H; }
        SEPARATOR { SCALE_H; }

        GROUP{

            SEPARATOR { SCALE_H; }

            LONG IF_MODE { CYCLE { IF_CIRCULAR; IF_V;}; SCALE_H; ANIM OFF;}

            SEPARATOR { SCALE_H; }

            GRADIENT IF_GRADIENT { OPEN; COLOR; ICC_BASEDOCUMENT; }

        }

        SEPARATOR IF_REFLECTION { SCALE_H; }
        SEPARATOR { SCALE_H; }

        GROUP{

            SEPARATOR { SCALE_H; }

            BOOL IF_ONOFF {ANIM OFF;}

            LONG IF_REF_MODE { CYCLE { IF_DIEL; IF_COND;}; SCALE_H; ANIM OFF;}

            REAL IF_STRENGTH {SCALE_H; ANIM OFF; MIN 0.0; MINEX; MAX 1000.0; MAXEX; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 1.0; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
            REAL IF_RUOGHNESS {SCALE_H; ANIM OFF; MIN 0.0; MINEX; MAX 1000.0; MAXEX; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 1.0; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
            REAL IF_FRESNEL_STRENGTH {SCALE_H; ANIM OFF; MIN 0.0; MINEX; MAX 1000.0; MAXEX; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 1.0; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
            REAL IF_IOR {SCALE_H; ANIM OFF; MIN 0.0; MINEX; MAX 10.0; MAXEX; MINSLIDER 0.0; MAXSLIDER 10.0; STEP 0.01; UNIT REAL; CUSTOMGUI REALSLIDER;}
            REAL IF_SAMPLING {SCALE_H; ANIM OFF; MIN 0.0; MINEX; MAX 32.0; MAXEX; MINSLIDER 0.0; MAXSLIDER 32.0; STEP 0.01; UNIT REAL; CUSTOMGUI REALSLIDER;}

            SEPARATOR { SCALE_H; }

            BOOL IF_DIM {ANIM OFF;}
            REAL IF_DIST {SCALE_H; ANIM OFF; MIN 0.0; MINEX; MAX 100000.0; MAXEX; MINSLIDER 0.0; MAXSLIDER 10000.0; STEP 1.0; UNIT METER; CUSTOMGUI REALSLIDER;}
            REAL IF_FALLOFF {SCALE_H; ANIM OFF; MIN -1.0; MINEX; MAX 1.0; MAXEX; MINSLIDER -1.0; MAXSLIDER 1.0; STEP 0.1; UNIT REAL; CUSTOMGUI REALSLIDER;}

        }

        SEPARATOR IF_SET { SCALE_H; }
        SEPARATOR { SCALE_H; }

        GROUP{

            SEPARATOR { SCALE_H; }

            GROUP{COLUMNS 2; SCALE_H;

                BOOL IF_ONOFF_FLOOR {ANIM OFF;}
                BOOL IF_ONOFF_BG {ANIM OFF;}

            }

        }

    }

}