CONTAINER OverheadSoftBox
{
    NAME OverheadSoftBox;
    INCLUDE Obase;


    GROUP ID_OBJECTPROPERTIES_OH
    {

        DEFAULT 1;

        STRING OH_RENDERER { ANIM OFF; CUSTOMGUI STATICTEXT; WORDWRAP;}

        GROUP{COLUMNS 2; SCALE_H;

            STATICTEXT OH_PE {SCALE_H;}
            BUTTON OH_HELP { SCALE_H;}

        }

        SEPARATOR OH_SETTINGS { SCALE_H; }
        SEPARATOR { SCALE_H; }

        GROUP{

            SEPARATOR { SCALE_H; }

            GROUP{COLUMNS 2;

                LONG OH_MODE { CYCLE { OH_SOFTBOX; OH_SPOT;}; SCALE_H; ANIM OFF;}
                BOOL OH_CAST {ANIM OFF;}
            
            }

        }

        GROUP{

            SEPARATOR { SCALE_H; }

            REAL OH_WIDTH {SCALE_H; ANIM OFF; MIN 1.0; MINEX; MAX 100000.0; MAXEX; MINSLIDER 1.0; MAXSLIDER 10000.0; STEP 1.0; UNIT METER; CUSTOMGUI REALSLIDER;}
            REAL OH_HIDTH {SCALE_H; ANIM OFF; MIN 1.0; MINEX; MAX 100000.0; MAXEX; MINSLIDER 1.0; MAXSLIDER 10000.0; STEP 1.0; UNIT METER; CUSTOMGUI REALSLIDER;}
            REAL OH_DIST {SCALE_H; ANIM OFF; MIN 100.0; MINEX; MAX 100000.0; MAXEX; MINSLIDER 100.0; MAXSLIDER 2500.0; STEP 1.0; UNIT METER; CUSTOMGUI REALSLIDER;}

        }

        SEPARATOR OH_LIGHT_SET{ SCALE_H; }
        SEPARATOR { SCALE_H; }

        GROUP{

            SEPARATOR { SCALE_H; }

            COLOR OH_LIGHT_COLOR { OPEN; PARENTCOLLAPSE; }

            SEPARATOR { SCALE_H;}

            GROUP{COLUMNS 3;

            BOOL OH_USED {ANIM OFF;}
            LINK OH_LINK {SCALE_H; ANIM OFF;}
            BOOL OH_INVERT_COLOR {ANIM OFF;}

            }

            SEPARATOR { SCALE_H; }

            REAL OH_BRIGHTNESS {SCALE_H; MIN 0.0; MINEX; MAX 10000.0; MAXEX; MINSLIDER 0.0; MAXSLIDER 200.0; STEP 1.0; UNIT PERCENT; CUSTOMGUI REALSLIDER;}

            SEPARATOR { SCALE_H; }
            
            GROUP{COLUMNS 2;

                BOOL OH_ADDGAIN {ANIM OFF;}
                REAL OH_SAMPLES {SCALE_H; ANIM OFF; MIN 0.0; MINEX; MAX 10000.0; MAXEX; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 1.0; UNIT REAL; CUSTOMGUI REALSLIDER;}

                BOOL OH_USED_BRIGHTNESS_PLANE {ANIM OFF;}
                REAL OH_BRIGHTNESS_PLANE{SCALE_H; MIN 0.0; MINEX; MAX 1000.0; MAXEX; MINSLIDER 0.0; MAXSLIDER 500.0; STEP 1.0; UNIT REAL; CUSTOMGUI REALSLIDER;}

                BOOL OH_SHOW_FALLOFF {ANIM OFF;}
                LONG OH_SHADOW_FALLOFF { CYCLE { OH_SHADOW_FALLOFF_INVERS; OH_SHADOW_FALLOFF_LINER; OH_SHADOW_FALLOFF_NONE; }; SCALE_H; ANIM OFF;}

            }


        }

        SEPARATOR OH_SHADOW_SET{ SCALE_H; }
        SEPARATOR { SCALE_H; }

        GROUP{ SCALE_H;

            SEPARATOR { SCALE_H; }

            SEPARATOR { SCALE_H; }

            GROUP {COLUMNS 3; SCALE_H;

                LONG OH_LIGHT_SHADOWTYPE { CYCLE { OH_SH_AREA; OH_SH_NONE; OH_SH_RAY; OH_SH_SOFT;}; ANIM OFF;}

                BOOL OH_LOCK {SCALE_H; ANIM OFF;}
                COLOR OH_SHADOW_COLOR { PARENTCOLLAPSE; ANIM OFF;}

            }

            SEPARATOR { SCALE_H; }

            REAL OH_SHADOW_DENSITY {SCALE_H; MIN 0.0; MINEX; MAX 10000.0; MAXEX; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 1.0; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
            REAL OH_SHADOW_VALUE {SCALE_H; MIN 0.0; MINEX; MAX 10000.0; MAXEX; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 1.0; UNIT PERCENT; CUSTOMGUI REALSLIDER;}

            GROUP {

                SEPARATOR { SCALE_H; }

                REAL OH_LIGHT_SHADOW_DENSITY {SCALE_H; ANIM OFF; MIN 0.0; MINEX; MAX 10000.0; MAXEX; MINSLIDER 0.0; MAXSLIDER 300.0; STEP 1.0; UNIT PERCENT; CUSTOMGUI REALSLIDER;}
                REAL OH_LIGHT_SHADOW_MAXSAMPLES {SCALE_H; ANIM OFF; MIN 0.0; MINEX; MAX 10000.0; MAXEX; MINSLIDER 0.0; MAXSLIDER 500.0; STEP 1.0; UNIT REAL; CUSTOMGUI REALSLIDER;}
                REAL OH_LIGHT_SHADOW_MAPSIZEX {SCALE_H; ANIM OFF; MIN 0.0; MINEX; MAX 10000.0; MAXEX; MINSLIDER 0.0; MAXSLIDER 500.0; STEP 1.0; UNIT REAL; CUSTOMGUI REALSLIDER;}

            }

        }

        SEPARATOR OH_COMPOSITING_SET { SCALE_H; }
        SEPARATOR { SCALE_H; }

        GROUP{

            SEPARATOR { SCALE_H; }

            GROUP { COLUMNS 3; SCALE_H;

                BOOL OH_OH_CAMERA {ANIM OFF;}
                BOOL OH_REFLECTION {ANIM OFF;}
                BOOL OH_SPECULAR {ANIM OFF;}
                BOOL OH_OH_TRANSPARENCY {ANIM OFF;}
                BOOL OH_LIGHT_ON {ANIM OFF;}
                BOOL OH_V_EDITOR {ANIM OFF;}

            }

        }


    }

    GROUP ID_OBJECTPROPERTIES_OH_PRO
    {


        LONG OH_LIGHT_PRO { CYCLE { OH_EXCLUDE; OH_INCLUDE;}; SCALE_H; ANIM OFF;}

        IN_EXCLUDE OH_LIGHT_OBJECT {SCALE_H; OPEN;}


    }


}